name: CI

on:
  push:
  release:
    types: [published]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Book PDF
        uses: hspaans/latexmk-action@v2.0.0
        with:
          format: pdf
          filename: My Math Memoir.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-book
          path: My Math Memoir.pdf

      - name: Upload to Release (Release Only)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            main.pdf
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
