name: LaTeX PDF Build & Clean Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-lang-all

    - name: Compile LaTeX to PDF
      run: pdflatex -interaction=nonstopmode "My_Math_Memoir.tex"

    - name: Prepare PDF for deployment
      run: |
        # Create a clean folder
        mkdir -p deploy
        # Move the PDF into the deploy folder
        mv "My_Math_Memoir.pdf" deploy/
        # Remove any other files from previous runs
        rm -rf deploy/*~ deploy/*.log deploy/*.aux

    - name: Deploy PDF to GitHub Pages
      uses: peaceiris/actions-gh-pages@v7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: deploy
        publish_branch: gh-pages
        keep_files: false  # ensures old files are removed
        user_name: github-actions
        user_email: github-actions@github.com
