name: LaTeX PDF Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-lang-all

    - name: Compile LaTeX to PDF
      run: pdflatex -interaction=nonstopmode "My_Math_Memoir.tex"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: My_Math_Memoir
        path: My_Math_Memoir.pdf
