name: Build LaTeX PDF

on:
  push:
    branches:
      - main   # runs on pushes to main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: My Math Memoir.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-PDF
          path: My Math Memoir.pdf
